name: Build f.Sentence

on:
  push:
    branches: [ main ]

jobs:
  build:
    if: contains(github.event.head_commit.message, '[build]')
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Setup Flutter
        uses: subosito/flutter-action@v2
        with:
          channel: 'stable'
          cache: true 

      - name: Decode Keystore
        run: echo "${{ secrets.KEYSTORE_BASE64 }}" | base64 --decode > android/app/f-sentence.jks

      - name: Install dependencies
        run: flutter pub get

      - name: Build APK
        run: flutter build apk --release --split-per-abi
        env:
          KEYSTORE_PASSWORD: ${{ secrets.KEYSTORE_PASSWORD }}
          KEY_ALIAS: ${{ secrets.KEY_ALIAS }}
          KEY_PASSWORD: ${{ secrets.KEY_PASSWORD }}

      # KORAK 3: Izvlačimo gotov, potpisan APK kao artifakt
      - name: Upload APK
        uses: actions/upload-artifact@v4
        with:
          name: f-sentence-release-apks
          path: build/app/outputs/flutter-apk/*.apk
          retention-days: 7
