name: Build f.Sentence

on:
  push:
    branches: [ main ]

jobs:
  build:
    if: contains(github.event.head_commit.message, '[build]')

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Setup Flutter
        uses: subosito/flutter-action@v2
        with:
          channel: 'stable'
          cache: true 

      - name: Install dependencies
        run: flutter pub get

      - name: Build APK
        # Dodajemo --release za svaki slučaj
        run: flutter build apk --release --split-per-abi

      - name: Upload APKs
        uses: actions/upload-artifact@v4
        with:
          name: f-sentence-apks
          path: build/app/outputs/flutter-apk/*.apk
          retention-days: 5
