name: Build f.Sentence

on:
  push:
    branches: [ main ]

jobs:
  build:
    # Build se pokreće SAMO ako poruka commit-a sadrži [build]
    if: contains(github.event.head_commit.message, '[build]')
    
    runs-on: ubuntu-latest
    
    steps:
      - uses: actions/checkout@v4

      - name: Setup Flutter
        uses: subosito/flutter-action@v2
        with:
          channel: 'stable'
          cache: true # Dodao sam keširanje da ti buildovi budu još brži

      - name: Install dependencies
        run: flutter pub get

      - name: Build APK
        run: flutter build apk --split-per-abi
        
